package Visual;

import Controlador.ControleJogo;
import Modelo.Usuario;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author klismam
 */
public class Jogo extends javax.swing.JFrame {

    public static Usuario usuario;

    public Jogo() {
        initComponents();
        Jogo.usuario = TelaLogin.usuario;
    }

    public static Usuario getUsuario() {
        return usuario;
    }

    public static void setUsuario(Usuario usuario) {
        Jogo.usuario = usuario;
    }

    public JButton getBtnTentar() {
        return btnTentar;
    }

    public void setBtnTentar(JButton btnTentar) {
        this.btnTentar = btnTentar;
    }

    public JButton getBtnVoltar() {
        return btnVoltar;
    }

    public void setBtnVoltar(JButton btnVoltar) {
        this.btnVoltar = btnVoltar;
    }

    public JLabel getImgforca() {
        return imgforca;
    }

    public void setImgforca(JLabel imgforca) {
        this.imgforca = imgforca;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JLabel getJlDicas() {
        return jlDicas;
    }

    public void setJlDicas(JLabel jlDicas) {
        this.jlDicas = jlDicas;
    }

    public JLabel getJlDificuldade() {
        return jlDificuldade;
    }

    public void setJlDificuldade(JLabel jlDificuldade) {
        this.jlDificuldade = jlDificuldade;
    }

    public JLabel getJlLetrasTentadas() {
        return jlLetrasTentadas;
    }

    public void setJlLetrasTentadas(JLabel jlLetrasTentadas) {
        this.jlLetrasTentadas = jlLetrasTentadas;
    }

    public JLabel getJlPalavraEscondida() {
        return jlPalavraEscondida;
    }

    public void setJlPalavraEscondida(JLabel jlPalavraEscondida) {
        this.jlPalavraEscondida = jlPalavraEscondida;
    }

    public JLabel getJlPontuacao() {
        return jlPontuacao;
    }

    public void setJlPontuacao(JLabel jlPontuacao) {
        this.jlPontuacao = jlPontuacao;
    }

    public JLabel getJlpontos() {
        return jlpontos;
    }

    public void setJlpontos(JLabel jlpontos) {
        this.jlpontos = jlpontos;
    }

    public JLabel getJltentativasRestantes() {
        return jltentativasRestantes;
    }

    public void setJltentativasRestantes(JLabel jltentativasRestantes) {
        this.jltentativasRestantes = jltentativasRestantes;
    }

    public JTextField getTxtPalavra() {
        return txtPalavra;
    }

    public void setTxtPalavra(JTextField txtPalavra) {
        this.txtPalavra = txtPalavra;
    }

    public JLabel getJlPontuacaoTotal() {
        return jlPontuacaoTotal;
    }

    public void setJlPontuacaoTotal(JLabel jlPontuacaoTotal) {
        this.jlPontuacaoTotal = jlPontuacaoTotal;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlPontuacao = new javax.swing.JLabel();
        imgforca = new javax.swing.JLabel();
        jlPalavraEscondida = new javax.swing.JLabel();
        jlDicas = new javax.swing.JLabel();
        txtPalavra = new javax.swing.JTextField();
        btnTentar = new javax.swing.JButton();
        jlLetrasTentadas = new javax.swing.JLabel();
        jlpontos = new javax.swing.JLabel();
        jltentativasRestantes = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlDificuldade = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jlPontuacaoTotal = new javax.swing.JLabel();
        imagem = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(580, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlPontuacao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlPontuacao.setForeground(new java.awt.Color(255, 255, 255));
        jlPontuacao.setText("Pontuação Parcial:");
        jPanel1.add(jlPontuacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, 20));

        imgforca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(imgforca, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 350, 350));

        jlPalavraEscondida.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlPalavraEscondida.setForeground(new java.awt.Color(255, 255, 255));
        jlPalavraEscondida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPalavraEscondida.setText("palavra escondida");
        jPanel1.add(jlPalavraEscondida, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 436, 470, 31));

        jlDicas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlDicas.setForeground(new java.awt.Color(255, 255, 255));
        jlDicas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlDicas.setText("Dicas");
        jPanel1.add(jlDicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 399, 62, -1));

        txtPalavra.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(txtPalavra, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 479, 57, -1));

        btnTentar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTentar.setText("Tentar");
        btnTentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTentarActionPerformed(evt);
            }
        });
        jPanel1.add(btnTentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 478, -1, -1));

        jlLetrasTentadas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlLetrasTentadas.setForeground(new java.awt.Color(255, 255, 255));
        jlLetrasTentadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlLetrasTentadas.setText("Letras Tentadas");
        jPanel1.add(jlLetrasTentadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 509, 251, 38));

        jlpontos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlpontos.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jlpontos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, 30, 20));

        jltentativasRestantes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jltentativasRestantes.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jltentativasRestantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 590, 40, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tentantivas Restantes:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, -1, 20));

        jlDificuldade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlDificuldade.setForeground(new java.awt.Color(255, 255, 255));
        jlDificuldade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlDificuldade.setText("Dificuldade");
        jPanel1.add(jlDificuldade, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 419, 74, -1));

        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pontuação Total:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, 20));

        jlPontuacaoTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlPontuacaoTotal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jlPontuacaoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 580, 30, 20));

        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visual/Jogo.jpg"))); // NOI18N
        jPanel1.add(imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTentarActionPerformed

    }//GEN-LAST:event_btnTentarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed

    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTentar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel imgforca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlDicas;
    private javax.swing.JLabel jlDificuldade;
    private javax.swing.JLabel jlLetrasTentadas;
    private javax.swing.JLabel jlPalavraEscondida;
    private javax.swing.JLabel jlPontuacao;
    private javax.swing.JLabel jlPontuacaoTotal;
    private javax.swing.JLabel jlpontos;
    private javax.swing.JLabel jltentativasRestantes;
    private javax.swing.JTextField txtPalavra;
    // End of variables declaration//GEN-END:variables
}
