package Visual;

import Modelo.Usuario;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author klismam
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public static Usuario usuario;

    public TelaLogin() {
        initComponents();
    }

    public static Usuario getUsuario() {
        return usuario;
    }

    public static void setUsuario(Usuario usuario) {
        TelaLogin.usuario = usuario;
    }

    public JLabel getCadastro() {
        return Cadastro;
    }

    public JButton getBtnVoltar() {
        return btnVoltar;
    }

    public void setBtnVoltar(JButton btnVoltar) {
        this.btnVoltar = btnVoltar;
    }
    
    public void setCadastro(JLabel Cadastro) {
        this.Cadastro = Cadastro;
    }

    public JButton getBtnCadastrar() {
        return btnCadastrar;
    }

    public void setBtnCadastrar(JButton btnCadastrar) {
        this.btnCadastrar = btnCadastrar;
    }

    public JButton getBtnLogar() {
        return btnLogar;
    }

    public void setBtnLogar(JButton btnLogar) {
        this.btnLogar = btnLogar;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPasswordField getTfConfirmaSenha() {
        return tfConfirmaSenha;
    }

    public void setTfConfirmaSenha(JPasswordField tfConfirmaSenha) {
        this.tfConfirmaSenha = tfConfirmaSenha;
    }

    public JTextField getTfLogin() {
        return tfLogin;
    }

    public void setTfLogin(JTextField tfLogin) {
        this.tfLogin = tfLogin;
    }

    public JTextField getTfLoginCadastro() {
        return tfLoginCadastro;
    }

    public void setTfLoginCadastro(JTextField tfLoginCadastro) {
        this.tfLoginCadastro = tfLoginCadastro;
    }

    public JTextField getTfNomeUsuario() {
        return tfNomeUsuario;
    }

    public void setTfNomeUsuario(JTextField tfNomeUsuario) {
        this.tfNomeUsuario = tfNomeUsuario;
    }

    public JPasswordField getTfSenhaCadastro() {
        return tfSenhaCadastro;
    }

    public void setTfSenhaCadastro(JPasswordField tfSenhaCadastro) {
        this.tfSenhaCadastro = tfSenhaCadastro;
    }

    public JPasswordField getTfSenhaLogin() {
        return tfSenhaLogin;
    }

    public void setTfSenhaLogin(JPasswordField tfSenhaLogin) {
        this.tfSenhaLogin = tfSenhaLogin;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Cadastro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfNomeUsuario = new javax.swing.JTextField();
        tfLogin = new javax.swing.JTextField();
        tfLoginCadastro = new javax.swing.JTextField();
        tfSenhaCadastro = new javax.swing.JPasswordField();
        tfSenhaLogin = new javax.swing.JPasswordField();
        btnLogar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfConfirmaSenha = new javax.swing.JPasswordField();
        btnVoltar = new javax.swing.JButton();
        imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(485, 300));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cadastro.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Cadastro.setForeground(new java.awt.Color(255, 255, 255));
        Cadastro.setText("Cadastro");
        jPanel1.add(Cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 110, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Senha:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nome de Usuario:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Login:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Senha:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 20));

        tfNomeUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(tfNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 80, 130, -1));

        tfLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(tfLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 130, -1));

        tfLoginCadastro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(tfLoginCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 190, -1));

        tfSenhaCadastro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(tfSenhaCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 190, -1));

        tfSenhaLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(tfSenhaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 130, -1));

        btnLogar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLogar.setText("Logar");
        btnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Confirmar Senha:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 20));

        tfConfirmaSenha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(tfConfirmaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 130, -1));

        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVoltar.setText("Voltar");
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visual/telalogin.jpg"))); // NOI18N
        jPanel1.add(imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarActionPerformed
        
    }//GEN-LAST:event_btnLogarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed


    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cadastro;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLogar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField tfConfirmaSenha;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JTextField tfLoginCadastro;
    private javax.swing.JTextField tfNomeUsuario;
    private javax.swing.JPasswordField tfSenhaCadastro;
    private javax.swing.JPasswordField tfSenhaLogin;
    // End of variables declaration//GEN-END:variables
}
