package Visual;

import Modelo.DAORanking;
import Modelo.SementeMysql;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author klismam
 */
public final class TelaRanking extends javax.swing.JFrame {

    /**
     * Creates new form TelaRanking
     */
    public TelaRanking() {
        initComponents();
        preencherTabela("select id_usuario, nome_usuario, melhorPontuacao, trofeu from usuario order by melhorPontuacao desc");
    }

    public void preencherTabela(String SQL) {

        Connection c = SementeMysql.getConexaoMySQL();

        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Id", "Nome", "Pontuação", "Trofeus"};

        try {
            Statement stm = c.createStatement();
            ResultSet rs = stm.executeQuery(SQL);
            rs.first();
            do {
                dados.add(new Object[]{rs.getInt("id_usuario"), rs.getString("nome_usuario"),
                    rs.getInt("melhorPontuacao"), rs.getInt("trofeu")});
            } while (rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Preencher o Array list !\nERRO: " + ex);
        }

        DAORanking modelo = new DAORanking(dados, Colunas);
        jTableRanking.setModel(modelo);
        jTableRanking.getColumnModel().getColumn(0).setPreferredWidth(80); // linha id
        jTableRanking.getColumnModel().getColumn(0).setResizable(false);
        jTableRanking.getColumnModel().getColumn(1).setPreferredWidth(80); // linha nome
        jTableRanking.getColumnModel().getColumn(1).setResizable(false);
        jTableRanking.getColumnModel().getColumn(2).setPreferredWidth(80); // linha da pontuação
        jTableRanking.getColumnModel().getColumn(2).setResizable(false);
        jTableRanking.getColumnModel().getColumn(3).setPreferredWidth(75); //linha trofeus
        jTableRanking.getColumnModel().getColumn(3).setResizable(false);
        jTableRanking.getTableHeader().setReorderingAllowed(false);
        jTableRanking.setAutoResizeMode(jTableRanking.AUTO_RESIZE_OFF);
        jTableRanking.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRanking = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableRanking);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 78, 320, 330));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ranking Dos Melhores");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 270, -1));

        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visual/ranking.jpg"))); // NOI18N
        jPanel1.add(imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRanking;
    // End of variables declaration//GEN-END:variables
}
